"""Add user_id to URLMapping

Revision ID: c69302ff70c0
Revises: 2b20ff809627
Create Date: 2024-06-29 17:43:09.148293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69302ff70c0'
down_revision = '2b20ff809627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # Update existing rows to have a default user_id, assuming user_id 1 exists
    op.execute('UPDATE url_mapping SET user_id = 1 WHERE user_id IS NULL')

    with op.batch_alter_table('url_mapping', schema=None) as batch_op:
        batch_op.alter_column('user_id', existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_mapping', schema=None) as batch_op:
        batch_op.drop_constraint(None, 'url_mapping', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###

